dbt_project:
  target: da909ge4nntude  # This will serve as your default environment
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('ENV') }}"
      schema: cdm