# dbt_project.yml

# Project Metadata
name: 'dbt_project'
version: '1.0.0'
config-version: 2

# Profile Configuration
profile: 'dbt_project'

# File Paths Configuration
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Model Configuration
models:
 dbt_project:
    # Exclude models in the 'example' directory
    example:
      enabled: false
    # Configuration for models in the 'cdm' directory
    cdm:
      enabled: true
      # Materialization strategy for models in the 'cdm' directory
      +materialized: table
    # Configuration for models in the 'raw' directory
    raw:
      enabled: true
      # Materialization strategy for models in the 'raw' directory
      +materialized: table

# Clean Targets Configuration
clean-targets:
 - "target"
 - "dbt_packages"

# Additional Model Configuration
# This section can be used to apply specific configurations to models
# within the 'cdm' and 'raw' directories or any other directory.
# For example, to exclude certain models from being built, you can use tags.
models:
 dbt_project:
    # Example of using tags to exclude models
    example:
      tags: ["exclude"]
