# Project Metadata
name: 'dbt_project'
version: '1.0.0'
config-version: 2

# Profile Configuration
profile: 'dbt_project'

# File Paths Configuration
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean Targets Configuration
clean-targets:
  - "target"
  - "dbt_packages"

# Set the default schema for all models
models:
  dbt_project:
    +database: "{{ env_var('ENV') }}"
    +schema: cdm  # Default schema for most models

    app:
      metrics:
        +schema: metrics  # Models in the metrics folder will go to metrics schema
      quality_checks:
        +schema: quality_checks  # Models in the quality_checks folder will go to quality_checks schema
