name: 'dbt_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Define models configuration
models:
  dbt_project: # This matches the `name` key at the top
    # Specific configurations for models in the 'raw' directory
    raw:
      +schema: 'raw'
      # Any additional configurations for 'raw' models go here
    # Specific configurations for models in the 'cdm' directory
    cdm:
      +schema: 'cdm'
      # Any additional configurations for 'cdm' models go here
    # Example directory is disabled, assuming you still want that
    example:
      enabled: false

clean-targets:
  - "target"
  - "dbt_packages"
